name: "1.0$(Rev:.r)"

trigger:
  - main
  - sonarcloud-test

variables:
  CI: "true"
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  solution: "genshin-api.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  appName: "genshin-api"
jobs:
  - job: build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UseDotNet@2
        displayName: Install .NET 5.0.x
        inputs:
          packageType: "sdk"
          version: "5.0.x"

      - task: DotNetCoreCLI@2
        displayName: Restore Packages
        inputs:
          command: "restore"
          projects: $(solution)
          feedsToUse: "select"
          verbosityRestore: "Minimal"

      - task: DotNetCoreCLI@2
        displayName: Build Solution
        inputs:
          command: "build"
          projects: $(solution)
          arguments: "-c $(buildConfiguration) --no-restore --nologo"

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: $(solution)
          arguments: '-c $(buildconfiguration) --no-build --nologo --collect "Code Coverage"'

      - task: DotNetCoreCLI@2
        displayName: Publish Solution
        inputs:
          command: "publish"
          projects: $(solution)
          arguments: "-c $(buildConfiguration) --no-build --nologo"
          zipAfterPublish: false

      - task: Docker@2
        displayName: Login to Docker
        inputs:
          command: login
          containerRegistry: "Docker Hub"

      - task: Docker@2
        displayName: Build and Push Docker Image
        inputs:
          containerRegistry: "Docker Hub"
          repository: jacksondr5/genshin-api
          command: buildAndPush
          Dockerfile: Dockerfile
          tags: |
            $(Build.BuildNumber)
            latest

  - job: analyze
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        displayName: Install .NET 5.0.x
        inputs:
          packageType: "sdk"
          version: "5.0.x"

      # Needed for SonarQube
      - task: UseDotNet@2
        displayName: Install .NET Core 2.2.x for SonarCloud
        inputs:
          packageType: "sdk"
          version: "2.2.x"

      - task: SonarCloudPrepare@1
        displayName: Prepare SonarCloud Analysis
        inputs:
          SonarCloud: "SonarCloud"
          organization: "jacksondr5"
          scannerMode: "MSBuild"
          projectKey: "Jacksondr5_genshin-api"
          projectName: "genshin-api"
          projectVersion: $(Build.BuildNumber)
          extraProperties: |
            sonar.coverage.exclusions=**/WebApi/**,**/Infrastructure/**

      - task: DotNetCoreCLI@2
        displayName: Restore Packages
        inputs:
          command: "restore"
          projects: $(solution)
          feedsToUse: "select"
          verbosityRestore: "Minimal"

      - task: DotNetCoreCLI@2
        displayName: Build Solution
        inputs:
          command: "build"
          projects: $(solution)
          arguments: "-c $(buildConfiguration) --no-restore --nologo"

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: $(solution)
          arguments: '-c $(buildconfiguration) --no-build --nologo --collect "Code Coverage"'

      - task: SonarCloudAnalyze@1
        displayName: Run SonarCloud Analysis

      - task: SonarCloudPublish@1
        displayName: Publish SonarCloud Analysis
        inputs:
          pollingTimeoutSec: "300"
